### ISSUE TITLE
Login Failed when try to download subtitile 

### ISSUE THREAD

**Issue by Enrico68** [mus65/subberthehut#6]
Whenever I try to download a subtitle I got this error 

```
login failed: Libwww HTPostAnchor() failed to start POST request (-504)
```

**Comment by mus65** [comment]
libwww? I have never heard of this library before, but it seems to be dead for years and xmlrpc-c discourages using it (http://xmlrpc-c.sourceforge.net/doc/libxmlrpc_client.html#libwww).

What distribution did you build this on? I highly doubt that this is actually a bug in subberthehut itself. Try building xmlrpc-c against libcurl instead of libwww.

**Comment by Enrico68** [comment]
mus65 <notifications@github.com> writes:

> libwww? I have never heard of this library before, but it seems to be dead for years and xmlrpc-c discourages using it (http://xmlrpc-c.sourceforge.net/doc/libxmlrpc_client.html#libwww).
>
> What distribution did you build this on? I highly doubt that this is actually a bug in subberthehut itself. Try building xmlrpc-c against libcurl instead of libwww.
OSX 10.9.5, this error is coming out after recompile this version...
> ---

**Comment by mus65** [comment]
did you mean to post an error message? Because I don't see any. And what exactly did you try to recompile? xmlrpc-c with libcurl?

Either way, I have no idea how the Unix stuff on OS X works, so I may not be able to help you here.
