### ISSUE TITLE
returned list of subtitles seems limited to 10 items

### ISSUE THREAD

**Issue by jackjackk** [mus65/subberthehut#7]
is it possible to extend it? how exactly is it sorted?

thanks a lot for this extremely useful app.

**Comment by mus65** [comment]
There already is the -t / --limit option for this (see subberthehut --help). Afaik the server allows 500 max.

subberthehut itself does not do any sorting, the subtitles are listed as returned by the server. I don't think the exact logic for sorting is even documented in the server API. Also the server API doesn't allow to specifiy any sorting option.

Do you need subberthehut to order the results itself? Even if I implement this, the results wouldn't exactly be what one would expect since sorting should always happen before limiting, but this is not possible due to the mentioned missing sorting options in the server API.

**Comment by jackjackk** [comment]
thanks, I incredibly missed that option.
No need for specific sorting, even though popularity and submission date may be reasonable sorting criteria.
What I actually would like to do is perhaps filter according to potential name pattern. Should I rename the video first, similarly to the sub file I want, or how do I grep the results if I want to include this into some non-interactive script?
Thanks a lot
